/**
 * アプリケーション全体のルートレイアウト
 * 全ページ共通のHTML構造、グローバルスタイル、Providerなどを定義
 */
import './globals.css';

import type { Metadata } from 'next';
import type { JSX } from 'react';

export const metadata: Metadata = {
  title: 'Next Vibe Template',
  description: 'Generated by create next app',
};

/**
 * ルートレイアウトコンポーネント
 * @param {object} props - プロパティ
 * @param {React.ReactNode} props.children - 子要素
 * @returns {JSX.Element} ルートレイアウト要素
 */
const RootLayout = ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
