name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.30
      - name: Install
        run: bun install --frozen-lockfile
      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/lockfile*') }}
      - name: Lint & Format
        run: bun run lint && bun run format --check
      - name: Type Check
        run: bunx tsc --noEmit
      - name: Unit and Component Tests
        run: bun run test:unit
      - name: API Tests
        run: bun run test:api
      - name: E2E Tests
        run: xvfb-run --auto-servernum --server-num=1 bun run test:e2e
